<a href="https://colab.research.google.com/github/ahui-ops/road_to_pytorch2/blob/main/Overview_of_TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
!pip list

Package                   Version
------------------------- -----------------
absl-py                   1.4.0
accelerate                1.12.0
aiofiles                  25.1.0
aiohappyeyeballs          2.6.1
aiohttp                   3.13.3
aiosignal                 1.4.0
altair                    5.5.0
annotated-types           0.7.0
anyio                     4.12.1
apsw                      3.51.2.0
apswutils                 0.1.2
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
array_record              0.8.3
arrow                     1.4.0
attrs                     25.4.0
audioread                 3.1.0
backcall                  0.2.0
beartype                  0.22.9
beautifulsoup4            4.13.5
betterproto               2.0.0b6
bleach                    6.3.0
blinker                   1.4
blis                      1.3.3
cachetools                6.2.4
catalogue                 2.0.10
certifi                   2026.1.4
cffi                      2.0.0
charset-no

# 1. Overview of Tensors

In [4]:
import torch
import numpy as np

# Lists
my_list = [[1,2,3],[3,2,4]]
my_list

[[1, 2, 3], [3, 2, 4]]

In [5]:
# Numpy arrays
np1 = np.random.rand(3,4) # generate a 3-col, 4-row matrix
np1

#np1.dtype # chk its variable type

array([[0.87469417, 0.89870444, 0.84204143, 0.48414093],
       [0.89658621, 0.40166647, 0.77351012, 0.15152895],
       [0.06506647, 0.83769427, 0.38467318, 0.66595195]])

In [6]:
# Tensors
tensor_2d = torch.randn(3,4)
tensor_2d.dtype

torch.float32

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

# 2. Reshape & slice

In [9]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Reshape & View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# Reshape if we not sure the number of items using -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch.reshape(3,-1) # even when the data in storage is not contiguous, it still works
my_torch2


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [21]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.reshape(2,5)
my_torch3[1] = 5783
my_torch4

tensor([[   0, 5783,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [30]:
# Slices
my_torch5 = torch.arange(10)
my_torch5[7]


tensor(7)

In [31]:
my_torch5 = my_torch5.reshape(5,-1)
my_torch5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [32]:
my_torch5[:,0]

tensor([0, 2, 4, 6, 8])

In [33]:
# Return column
my_torch5[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# 3. Tensor Math operation


In [18]:
import torch
import numpy as np

tensorA = torch.tensor([1,2,3])
tensorB = torch.tensor([4,5,6])

# addition
tensorA + tensorB

# addition longhand 1
torch.add(tensorA,tensorB)

# addition longhand 2
tensorA.add(tensorB)

# local operation 1
tensorA = torch.add(tensorA,tensorB)

# local operation 2
tensorA.add_(tensorB)


tensor([ 9, 12, 15])

In [12]:
# subtraction
tensorB - tensorA

# subtraction longhand
torch.sub(tensorA,tensorB)

tensor([-3, -3, -3])

In [6]:
# multiplication
torch.mul(tensorA,tensorB)

tensor([ 4, 10, 18])

In [7]:
# division
torch.div(tensorA,tensorB)

tensor([0.2500, 0.4000, 0.5000])

In [9]:
# modulus
torch.remainder(tensorB,tensorA)

tensor([0, 1, 0])

In [10]:
# exponent
torch.pow(tensorA,tensorB)

tensor([  1,  32, 729])